# Generated by Django 3.1.6 on 2021-02-03 17:04

import uuid

import django.db.models.deletion
from django.db import migrations, models

import pipeline.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KerasModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="", max_length=250)),
                ("description", models.TextField(default="")),
                ("definition", models.JSONField(blank=True, default=dict)),
                (
                    "model",
                    models.FileField(
                        editable=False,
                        null=True,
                        upload_to=pipeline.models.kerasmodel_upload_to,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TrainingData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="", max_length=250)),
                ("description", models.TextField(default="")),
                (
                    "zipfile",
                    models.FileField(upload_to=pipeline.models.trainingdata_upload_to),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PixelsData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="", max_length=250)),
                ("description", models.TextField(default="")),
                ("config", models.JSONField(default=dict)),
                (
                    "trainingdata",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pipeline.trainingdata",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
