LOG_GROUP_NAME = "/aws/batch/job"
BATCH_JOB_ID_KEY = "jobId"

UNKNOWN = "UNKNOWN"
SUBMITTED = "SUBMITTED"
PENDING = "PENDING"
RUNNABLE = "RUNNABLE"
STARTING = "STARTING"
RUNNING = "RUNNING"
SUCCEEDED = "SUCCEEDED"
FAILED = "FAILED"

BATCH_JOB_RUNNING_STATUSES = [SUBMITTED, PENDING, RUNNABLE, STARTING, RUNNING]
BATCH_JOB_FINAL_STATUSES = [SUCCEEDED, FAILED]
BATCH_JOB_RUNNABLE_STATUSES = [UNKNOWN, SUCCEEDED, FAILED]
