# Generated by Django 3.1.6 on 2021-02-03 23:43

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BatchJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now=True)),
                ("job_id", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "SUBMITTED"),
                            ("PENDING", "PENDING"),
                            ("RUNNABLE", "RUNNABLE"),
                            ("STARTING", "STARTING"),
                            ("RUNNING", "RUNNING"),
                            ("SUCCEEDED", "SUCCEEDED"),
                            ("FAILED", "FAILED"),
                        ],
                        default="SUBMITTED",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField()),
                ("log_stream_name", models.CharField(max_length=1500)),
            ],
        ),
    ]
