# Generated by Django 3.1.6 on 2021-02-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batch", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchjob",
            name="description",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="batchjob",
            name="log_stream_name",
            field=models.CharField(blank=True, default="", max_length=1500),
        ),
    ]
