# Generated by Django 3.1.6 on 2021-02-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batch", "0002_auto_20210206_1436"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batchjob",
            name="created",
        ),
        migrations.AlterField(
            model_name="batchjob",
            name="job_id",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="batchjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUBMITTED", "SUBMITTED"),
                    ("PENDING", "PENDING"),
                    ("RUNNABLE", "RUNNABLE"),
                    ("STARTING", "STARTING"),
                    ("RUNNING", "RUNNING"),
                    ("SUCCEEDED", "SUCCEEDED"),
                    ("FAILED", "FAILED"),
                ],
                default="UNKNOWN",
                max_length=100,
            ),
        ),
    ]
