# Generated by Django 3.1.6 on 2021-08-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batch", "0003_auto_20210206_1443"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "UNKNOWN"),
                    ("SUBMITTED", "SUBMITTED"),
                    ("PENDING", "PENDING"),
                    ("RUNNABLE", "RUNNABLE"),
                    ("STARTING", "STARTING"),
                    ("RUNNING", "RUNNING"),
                    ("SUCCEEDED", "SUCCEEDED"),
                    ("FAILED", "FAILED"),
                ],
                default="UNKNOWN",
                max_length=100,
            ),
        ),
    ]
