# Generated by Django 3.1.6 on 2021-08-05 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batch", "0004_auto_20210804_1747"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchjob",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
