# Generated by Django 3.1.6 on 2021-08-18 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("batch", "0005_batchjob_created"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="batchjob",
            options={"ordering": ["-created"]},
        ),
    ]
