# Generated by Django 3.1.6 on 2021-02-03 23:43

import uuid

import django.db.models.deletion
import pipeline.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("batch", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="", max_length=250)),
                ("description", models.TextField(default="")),
                (
                    "zipfile",
                    models.FileField(
                        upload_to=pipeline.models.training_data_zip_upload_to
                    ),
                ),
                (
                    "batchjob",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="batch.batchjob",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PixelsData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="", max_length=250)),
                ("description", models.TextField(default="")),
                ("config", models.JSONField(default=dict)),
                (
                    "config_file",
                    models.FileField(
                        editable=False,
                        null=True,
                        upload_to=pipeline.models.pixels_data_json_upload_to,
                    ),
                ),
                (
                    "trainingdata",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pipeline.trainingdata",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KerasModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="", max_length=250)),
                ("description", models.TextField(default="")),
                ("definition", models.JSONField(blank=True, default=dict)),
                (
                    "model_h5",
                    models.FileField(
                        editable=False,
                        null=True,
                        upload_to="keras_model_h5_upload_to",
                    ),
                ),
                (
                    "model_json",
                    models.FileField(
                        editable=False,
                        null=True,
                        upload_to="keras_model_json_upload_to",
                    ),
                ),
                (
                    "batchjob",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="batch.batchjob",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
