# Generated by Django 3.1.6 on 2021-02-06 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trainingdata",
            old_name="batchjob",
            new_name="batchjob_parse",
        ),
        migrations.RemoveField(
            model_name="kerasmodel",
            name="batchjob",
        ),
    ]
