# Generated by Django 3.1.6 on 2021-02-07 17:14

from django.db import migrations, models
import pipeline.models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_auto_20210206_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingdata',
            name='reference_date',
            field=models.DateField(blank=True, help_text='Set a reference date for all input tiles. Will be used by the stac parser.', null=True),
        ),
        migrations.AlterField(
            model_name='kerasmodel',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Detailed description of the object.'),
        ),
        migrations.AlterField(
            model_name='kerasmodel',
            name='name',
            field=models.CharField(help_text='Short name of the object.', max_length=250),
        ),
        migrations.AlterField(
            model_name='pixelsdata',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Detailed description of the object.'),
        ),
        migrations.AlterField(
            model_name='pixelsdata',
            name='name',
            field=models.CharField(help_text='Short name of the object.', max_length=250),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Detailed description of the object.'),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='name',
            field=models.CharField(help_text='Short name of the object.', max_length=250),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='zipfile',
            field=models.FileField(help_text='A zip file containing the training data.', upload_to=pipeline.models.training_data_zip_upload_to),
        ),
    ]
