# Generated by Django 3.1.6 on 2021-02-07 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batch", "0003_auto_20210206_1443"),
        ("pipeline", "0003_auto_20210207_1714"),
    ]

    operations = [
        migrations.AddField(
            model_name="pixelsdata",
            name="batchjob_collect_pixels",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pixels_data_collect",
                to="batch.batchjob",
            ),
        ),
        migrations.AddField(
            model_name="pixelsdata",
            name="batchjob_create_catalog",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pixels_data_catalog",
                to="batch.batchjob",
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="batchjob_parse",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Background job that creates a STAC catalog from the input data.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="batch.batchjob",
            ),
        ),
    ]
