# Generated by Django 3.1.6 on 2021-02-12 19:09

import django.db.models.deletion
import pipeline.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0005_auto_20210211_1759"),
    ]

    operations = [
        migrations.AddField(
            model_name="kerasmodel",
            name="generator_arguments",
            field=models.FileField(
                editable=False,
                null=True,
                upload_to=pipeline.models.model_generator_arguments_file_upload_to,
            ),
        ),
        migrations.AddField(
            model_name="kerasmodel",
            name="pixelsdata",
            field=models.ForeignKey(
                default="2d3c6f57-febd-4a75-ba7f-4f49099c2a21",
                on_delete=django.db.models.deletion.PROTECT,
                to="pipeline.pixelsdata",
            ),
            preserve_default=False,
        ),
    ]
