# Generated by Django 3.1.6 on 2021-02-23 17:06

import pipeline.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0006_auto_20210212_1909"),
    ]

    operations = [
        migrations.AddField(
            model_name="kerasmodel",
            name="generator_arguments_file",
            field=models.FileField(
                editable=False,
                null=True,
                upload_to=pipeline.models.generator_arguments_file_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="kerasmodel",
            name="generator_arguments",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
