# Generated by Django 3.1.6 on 2021-05-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0008_prediction"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingdata",
            name="categorical",
            field=models.BooleanField(
                default=True,
                help_text="Determines if the training data is categorical or continuous.",
            ),
        ),
    ]
