# Generated by Django 3.1.6 on 2021-08-18 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0010_auto_20210805_1652"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kerasmodel",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterModelOptions(
            name="pixelsdata",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterModelOptions(
            name="prediction",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterModelOptions(
            name="trainingdata",
            options={"ordering": ["-created"]},
        ),
        migrations.RemoveField(
            model_name="prediction",
            name="batchjob_create_catalog",
        ),
    ]
