name: Continuous Integration for PxAPI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Checkout pxapi
        uses: actions/checkout@v2
        with:
          path: ./pxapi
      - name: Checkout pixels
        uses: actions/checkout@v2
        with:
          repository: tesselo/pixels
          ref: 2b7f7dde291008ef3529dcda51226cad9ccf6a8e
          token: ${{ secrets.ACCESS_TOKEN_PRIVATE_REPOS }}
          path: ./pixels
      - name: Install linters
        run: pip install isort black flake8
      - name: Lint with Flake8
        run: cd ./pxapi && flake8 pxapi
      - name: Lint with isort
        run: isort --check --diff pxapi
      - name: Lint with black
        run: black --check --diff pxapi
      - name: Install deps
        run: |
          pip install ./pixels
          pip install -r ./pxapi/requirements.txt
      - name: Test
        run: python ./pxapi/manage.py test ./pxapi/tests

  deploy:
    name: Deploy
    needs: [test]
    runs-on: ubuntu-latest
    if: contains('refs/heads/main', github.ref)
    steps:
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Checkout pxapi
        uses: actions/checkout@v2
        with:
          path: ./pxapi
      - name: Checkout pixels
        uses: actions/checkout@v2
        with:
          repository: tesselo/pixels
          ref: 2b7f7dde291008ef3529dcda51226cad9ccf6a8e
          token: ${{ secrets.ACCESS_TOKEN_PRIVATE_REPOS }}
          path: ./pixels
      - name: Create virtualenv and install deps
        run: |
          python -m pip install --upgrade pip virtualenv
          virtualenv -p /usr/bin/python3 ./pxapi-venv
          source ./pxapi-venv/bin/activate
          pip install ./pixels
          pip install -r ./pxapi/requirements.txt
      - name: Deploy
        run: |
          source ./pxapi-venv/bin/activate
          cd ./pxapi
          zappa update dev --disable_progress
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
